# 数据操作

In [18]:
import torch
print(torch.__version__)

1.6.0


## 创建Tensor

In [19]:
torch.empty(5, 3)

tensor([[9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0286e-38],
        [9.4592e-39, 9.2755e-39, 1.0653e-38],
        [8.4490e-39, 9.2755e-39, 9.2756e-39]])

In [20]:
torch.rand(5, 3)

tensor([[0.5897, 0.5081, 0.1343],
        [0.1882, 0.3719, 0.8727],
        [0.4961, 0.3528, 0.2107],
        [0.7690, 0.9004, 0.3848],
        [0.8497, 0.2858, 0.6684]])

In [21]:
torch.zeros(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.tensor([5, 3.2])

tensor([5.0000, 3.2000])

In [24]:
x = torch.rand(5, 3)
print(x)
y = torch.tensor(x)
print(y)
x = x + 1
print(x)
print(y)

tensor([[0.6215, 0.3859, 0.2711],
        [0.5395, 0.4195, 0.5124],
        [0.9558, 0.4669, 0.6115],
        [0.1551, 0.9374, 0.8943],
        [0.3990, 0.7648, 0.1181]])
tensor([[0.6215, 0.3859, 0.2711],
        [0.5395, 0.4195, 0.5124],
        [0.9558, 0.4669, 0.6115],
        [0.1551, 0.9374, 0.8943],
        [0.3990, 0.7648, 0.1181]])
tensor([[1.6215, 1.3859, 1.2711],
        [1.5395, 1.4195, 1.5124],
        [1.9558, 1.4669, 1.6115],
        [1.1551, 1.9374, 1.8943],
        [1.3990, 1.7648, 1.1181]])
tensor([[0.6215, 0.3859, 0.2711],
        [0.5395, 0.4195, 0.5124],
        [0.9558, 0.4669, 0.6115],
        [0.1551, 0.9374, 0.8943],
        [0.3990, 0.7648, 0.1181]])


## 看形状

In [25]:
x.size()

torch.Size([5, 3])

In [26]:
x.shape

torch.Size([5, 3])

## 算数操作

In [29]:
a = torch.rand(5, 3)
b = torch.rand(5, 3)
print('a:')
print(a)
print('b:')
print(b)
print('a+b:')
print(a + b)
print(torch.add(a, b))
print(a.add_(b))

a:
tensor([[0.7008, 0.2685, 0.0909],
        [0.1638, 0.7049, 0.6193],
        [0.2007, 0.4356, 0.9363],
        [0.3070, 0.0761, 0.2846],
        [0.6915, 0.4346, 0.7149]])
b:
tensor([[0.0370, 0.6029, 0.5781],
        [0.9956, 0.6245, 0.4870],
        [0.9934, 0.3533, 0.2711],
        [0.4895, 0.8348, 0.4540],
        [0.6055, 0.4929, 0.4474]])
a+b:
tensor([[0.7379, 0.8714, 0.6690],
        [1.1594, 1.3294, 1.1064],
        [1.1942, 0.7889, 1.2075],
        [0.7965, 0.9109, 0.7386],
        [1.2970, 0.9276, 1.1623]])
tensor([[0.7379, 0.8714, 0.6690],
        [1.1594, 1.3294, 1.1064],
        [1.1942, 0.7889, 1.2075],
        [0.7965, 0.9109, 0.7386],
        [1.2970, 0.9276, 1.1623]])
tensor([[0.7379, 0.8714, 0.6690],
        [1.1594, 1.3294, 1.1064],
        [1.1942, 0.7889, 1.2075],
        [0.7965, 0.9109, 0.7386],
        [1.2970, 0.9276, 1.1623]])


## 索引

In [35]:
a = torch.rand(5, 3)
print(a)

b = a[0, :]
print(b)

# 其共享内存
b += 1
print(a)
print(b)

tensor([[0.1018, 0.0732, 0.9403],
        [0.9620, 0.8203, 0.6471],
        [0.8468, 0.7040, 0.9371],
        [0.0120, 0.3451, 0.1076],
        [0.5409, 0.0251, 0.1531]])
tensor([0.1018, 0.0732, 0.9403])
tensor([[1.1018, 1.0732, 1.9403],
        [0.9620, 0.8203, 0.6471],
        [0.8468, 0.7040, 0.9371],
        [0.0120, 0.3451, 0.1076],
        [0.5409, 0.0251, 0.1531]])
tensor([1.1018, 1.0732, 1.9403])
tensor([[ 0.1018,  0.0732,  0.9403],
        [-0.0380, -0.1797, -0.3529],
        [-0.1532, -0.2960, -0.0629],
        [-0.9880, -0.6549, -0.8924],
        [-0.4591, -0.9749, -0.8469]])
tensor([0.1018, 0.0732, 0.9403])


## 改变形状

In [37]:
x = torch.rand(5, 3)
print(x.size())
y = x.view(-1, 5)
print(y.size())
# 依旧共享内存
x += 1
print(x)
print(y)
# 若要不共享，可以选择使用clone
y = x.clone().view(-1, 5)
x += 1
print(x)
print(y)

torch.Size([5, 3])
torch.Size([3, 5])
tensor([[1.9155, 1.4659, 1.9620],
        [1.2890, 1.9271, 1.2951],
        [1.6972, 1.1101, 1.6667],
        [1.4789, 1.0590, 1.8330],
        [1.2987, 1.3256, 1.1104]])
tensor([[1.9155, 1.4659, 1.9620, 1.2890, 1.9271],
        [1.2951, 1.6972, 1.1101, 1.6667, 1.4789],
        [1.0590, 1.8330, 1.2987, 1.3256, 1.1104]])
tensor([[2.9155, 2.4659, 2.9620],
        [2.2890, 2.9271, 2.2951],
        [2.6972, 2.1101, 2.6667],
        [2.4789, 2.0590, 2.8330],
        [2.2987, 2.3256, 2.1104]])
tensor([[1.9155, 1.4659, 1.9620, 1.2890, 1.9271],
        [1.2951, 1.6972, 1.1101, 1.6667, 1.4789],
        [1.0590, 1.8330, 1.2987, 1.3256, 1.1104]])


## Tensor和Numpy互换

In [38]:
import numpy as np
a = torch.rand(5, 3)
b = a.numpy()
print(a)
print(b)
# 它们两个依旧共享内存

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

tensor([[0.9638, 0.5980, 0.4349],
        [0.8199, 0.3134, 0.0441],
        [0.5306, 0.3088, 0.0197],
        [0.9394, 0.2022, 0.2792],
        [0.1768, 0.8214, 0.0580]])
[[0.9638411  0.5980037  0.4348811 ]
 [0.8198872  0.313411   0.04412693]
 [0.5306272  0.30884075 0.01966816]
 [0.93938863 0.2021733  0.2792294 ]
 [0.1767714  0.82144856 0.05802971]]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## tensor on gpu

In [39]:
device = torch.device("cuda")
x = torch.rand(5, 3)
print(x)
y = torch.ones_like(x, device=device)
print(y)

tensor([[0.3803, 0.6431, 0.3967],
        [0.7907, 0.0030, 0.7056],
        [0.6722, 0.2931, 0.8515],
        [0.0947, 0.8922, 0.3683],
        [0.3775, 0.9959, 0.3859]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
